### ISSUE TITLE
TCA9548 - change frequency - fast mode

### ISSUE THREAD

**Issue by SimonaGandah** [RobTillaart/TCA9548#11]
Hi I need to increase the acquisition frequency in my application in which I have multiple sensors connected to the TCA9548A, by using the available library my frequency is slow, How can i get the switching frequency of the multiplexer? And how to operate in fast mode?
Thank you

**Comment by RobTillaart** [comment]
Thanks for the issue,

Which board are you using?
If the sensors can have multiple addresses it is faster to keep them on a single I2C channel

Furthermore you might improve by using **Wire.setClock()**
See - https://www.arduino.cc/reference/en/language/functions/communication/wire/setclock/

If that is not fast enough you might have a look at - https://github.com/RobTillaart/HC4052
That will switch faster but takes more pins.

**Comment by RobTillaart** [comment]
@Anomis28 

As I didn't get answer on my question I assume the issue is solved.
Feel free to reopen the issue if needed.
