### ISSUE TITLE
Tested with PCA9548A; No issue found.

### ISSUE THREAD

**Issue by OptifySudarshanPatil** [RobTillaart/TCA9548#7]
Hi @RobTillaart ,
Recently checked out this library with PCA9548A  and working satisfactory.
No major issue detected.
```cpp
if (!MP.isConnected())
{
MP.reset();
    if (MP.begin() == false)
    {
      Serial.println("MUX  COULD NOT CONNECT");
      return;
    }
  }
```

**Comment by RobTillaart** [comment]
Thanks for this positive feedback!

What do you mean by the code snippet?
Is there a question?

**Comment by OptifySudarshanPatil** [comment]
> Is there a question?

No!
It's part of my code; in which I've tested function of library.
Added as reference for any one who might in need.

**Comment by RobTillaart** [comment]
OK, as there is no problem I'll close the issue.

Thanks again for the positive feedback
