### ISSUE TITLE
ambiguity in the call to the requestFrom function

### ISSUE THREAD

**Issue by KarenColumbo** [RobTillaart/TCA9548#8]
I get this WARNING when compiling from Teensy 4.1:
pio/libdeps/teensy41/TCA9548/TCA9548.cpp: In member function 'uint8_t TCA9548::getChannelMask()':
.pio/libdeps/teensy41/TCA9548/TCA9548.cpp:121:35: warning: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second: _wire->requestFrom(_address, 1);

.platformio/packages/framework-arduinoteensy/libraries/Wire/WireIMXRT.h:102:10: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
  uint8_t requestFrom(int address, int quantity) {

.platformio/packages/framework-arduinoteensy/libraries/Wire/WireIMXRT.h:95:10: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
  uint8_t requestFrom(uint8_t address, uint8_t quantity) {

**Comment by RobTillaart** [comment]
Thanks for raising the issue. Not tested the lib with teensy but seen this before in another lib an another platform. Will try to fix it tomorrow

**Comment by KarenColumbo** [comment]
No stress, just thought I'd bring it to attention. Program compiles fine. Thanks for the head-up and your work!
Am 11. Feb. 2023, 19:09 +0100 schrieb Rob Tillaart ***@***.***>:

**Comment by RobTillaart** [comment]
Thanks for your support!

I'm working on a (minor) new version, just have to look if there is some "low hanging fruit" I can include (without risk).

**Comment by RobTillaart** [comment]
Installed teensy board and tested and ambiguity seems solved in 0.1.5

If there are other issues please let me know!

**Comment by KarenColumbo** [comment]
thank you for your work!
